### ISSUE TITLE
Julia v1.9: ControlSystems/-MTK error message

### ISSUE THREAD

**Issue by B-LIE** [JuliaControl/ControlSystems.jl#834] opened 2023-05-11 06:37 UTC
The following command worked in Julia v1.8.5, but gives an error message in Julia v1.9/latest update of ControlSystems packages (CS: v1.7.2, CSMTK: v0.1.12):
<img width="415" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/5ffd9f1e-d86b-4975-a62d-b483146cf1af">

There is a warning during precompilation:
<img width="589" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/cfc7b7ea-add1-453b-987b-249e1b32e75d">

**Comment by B-LIE** [comment] 2023-05-11 06:56
Hm... the problem seems to be with `minreal`. If I remove piping the linearized model to `minreal`, the code runs, and I get the following bode plot:
<img width="476" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/040edeed-4136-4682-b3d2-40873fbc6f72">

When I *included* the call to `minreal` (Julia v1.8.5), the result was a somewhat different `bodeplot` (which is strange...):
<img width="454" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/56382433-1c8a-4064-b94c-1f1be1f18078">

**Comment by albheim** [comment] 2023-05-11 07:21
How does it look without `minreal` on 1.8.5, is it just `minreal` that does the difference or has something changed with newer versions? 
It seems `minreal` takes some tolerance, so I assume it could simplify away some states that does not exactly cancel depending on the tolerance, though I don't really have a clue.

Can you run `minreal` on a normal state space from ControlSystems.jl, e.g. `minreal(ssrand(1, 1, 3))`, or do you get the same error there?

**Comment by mzaffalon** [comment] 2023-05-11 07:45
> Not a good excuse for not learning about projects and toml, I know...

It is as easy as creating a new directory, starting the Julia version you want, hitting "]" so that the prompt changes to `pkg>` and type `add ControlSystems`. You can pin a ControlSystems version, e.g. v1.7.0, by using `pin ControlSystems@v1.7.0`.

Could you please paste the code (in a block of three backticks) instead of making a screenshot?

**Comment by B-LIE** [comment] 2023-05-11 07:55
OK... part of my "problem" with installing various versions of Julia packages is the following...
* The documentation is good on doing this in the documentation of `Pkg.jl`, i.e., to manage projects.
* I don't know where to find documentation on how to specify the *Julia* version -- the `toml`?

The reason why this is important: 1-2 years ago, I updated to a new version of Julia, and then it took several months before package `Turing.jl` worked with the new Julia version. It is not realistic that a user *remembers* which Julia version to use for a specific package version, so it is important to be able to package both the specification of the package version number and the Julia version number. 

And... I don't know where the documentation for specifying the Julia version is to be found...
##
OK -- here is the code I used:
``` julia
sys_test = ss([-1 2 3; 0 -2 3; 0 0 -3], [1;2;3], [1 2 3], [0])

minreal(sys_test)
```

**Comment by mzaffalon** [comment] 2023-05-11 08:02
Maybe [here](https://pkgdocs.julialang.org/v1/compatibility/) and using in the `Project.toml` file

```
[compat]
julia = "=1.8.5"
```
?

**Comment by baggepinnen** [comment] 2023-05-11 08:46
The warnings during precompilation are unrelated. What system is you on? If MacOS, are you running one of their newer ARM processors? The code works on my machine under both Julia 1.8.5 and 1.9.

`minreal` is implemented in MatrixPencils.jl and, as Albin says, takes a number of tolerance arguments that can be tweaked to get your desired results.

**Comment by baggepinnen** [comment] 2023-05-11 08:52
Could you try deleting your entire `.julia/compiled` folder and then issue `pkg> precompile` to re-do all precompilation? Your compilation cache might have ended up in a bad state or something.

**Comment by B-LIE** [comment] 2023-05-11 08:57
OK -- 
<img width="174" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/6c126606-a921-492f-9457-4163c718255d">

So 
1. I select subfolder `compiled` under directory `.julia` and delete it, and 
2. Run the `precompile` command in the `Pkg` package.

I'll do that. (I'll rename the `compiled` folder in case I get a problem...)

**Comment by B-LIE** [comment] 2023-05-11 09:16
OK -- I have recompiled. Here are the packages that I have installed at the moment:
<img width="439" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/3ecf9040-e1cf-4357-be0b-03f50d32d8ac">

I get the same error message as before:
<img width="372" alt="image" src="https://github.com/JuliaControl/ControlSystems.jl/assets/54220415/d3edf7f2-e8cd-4797-8539-6275a870038b">

**Comment by baggepinnen** [comment] 2023-05-11 09:24
what's the full output of `pkg> st -m`? Preferably as text rather than as screenshots, text is *always* preferable ;)

**Comment by baggepinnen** [comment] 2023-05-11 09:26
The issue is likely related to 
https://github.com/andreasvarga/MatrixPencils.jl/blob/460e14a529b7c300dca4917cefcca94e5d0c0ee5/src/lapackutil2.jl#L3

I'll open an issue in MatrixPencils.jl and close this one here

**Comment by B-LIE** [comment] 2023-05-11 09:27
Here it is:
```julia
(@v1.9) pkg> st -m
Status `C:\Users\Bernt\.julia\environments\v1.9\Manifest.toml`
⌅ [c3fe647b] AbstractAlgebra v0.29.4
  [621f4979] AbstractFFTs v1.3.1
  [1520ce14] AbstractTrees v0.4.4
  [79e6a3ab] Adapt v3.6.1
  [ec485272] ArnoldiMethod v0.2.0
  [4fba245c] ArrayInterface v7.4.3
  [30b0a656] ArrayInterfaceCore v0.1.29
⌃ [4c555306] ArrayLayouts v0.8.18
⌃ [aae01518] BandedMatrices v0.17.18
  [e2ed5e7c] Bijections v0.1.4
  [d1d4a3ce] BitFlags v0.1.7
  [62783981] BitTwiddlingConvenienceFunctions v0.1.5
  [764a87c0] BoundaryValueDiffEq v2.11.0
  [fa961155] CEnum v0.4.2
  [2a0fbf3d] CPUSummary v0.2.2
  [00ebfdb7] CSTParser v3.3.6
  [49dc2e85] Calculus v0.5.1
  [d360d2e6] ChainRulesCore v1.16.0
  [fb6a15b2] CloseOpenIntervals v0.1.12
  [944b1d66] CodecZlib v0.7.1
  [35d6a980] ColorSchemes v3.21.0
  [3da002f7] ColorTypes v0.11.4
  [c3611d14] ColorVectorSpace v0.9.10
  [5ae59095] Colors v0.12.10
  [861a8166] Combinatorics v1.0.2
  [a80b9123] CommonMark v0.8.12
  [38540f10] CommonSolve v0.2.3
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v4.6.1
  [b0b7db55] ComponentArrays v0.13.12
  [b152e2b5] CompositeTypes v0.1.3
  [f0e56b4a] ConcurrentUtilities v2.2.0
  [187b0558] ConstructionBase v1.5.2
  [d38c429a] Contour v0.6.2
  [a6e380b2] ControlSystems v1.7.2
  [aaaaaaaa] ControlSystemsBase v1.4.2
  [687d7614] ControlSystemsMTK v0.1.12
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [717857b8] DSP v0.7.8
  [9a962f9c] DataAPI v1.14.0
  [82cc6244] DataInterpolations v4.0.0
  [864edb3b] DataStructures v0.18.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [bcd4f6db] DelayDiffEq v5.42.0
  [8bb1440f] DelimitedFiles v1.9.1
  [a81e2ce2] DescriptorSystems v1.3.7
  [2b5f629d] DiffEqBase v6.124.0
  [459566f4] DiffEqCallbacks v2.26.1
  [77a26b50] DiffEqNoiseProcess v5.16.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.13.0
  [0c46a032] DifferentialEquations v7.7.0
  [b4f34e82] Distances v0.10.8
  [31c24e10] Distributions v0.25.90
  [ffbed154] DocStringExtensions v0.9.3
  [5b8099bc] DomainSets v0.6.6
  [fa6b7ba4] DualNumbers v0.6.8
  [7c1d4256] DynamicPolynomials v0.4.6
  [4e289a0a] EnumX v1.0.4
  [d4d017d3] ExponentialUtilities v1.24.0
  [e2ba6199] ExprTools v0.1.9
  [c87230d0] FFMPEG v0.4.1
  [7a1cc6ca] FFTW v1.6.0
  [7034ab61] FastBroadcast v0.2.5
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v1.2.9
⌅ [1a297f60] FillArrays v0.13.11
  [6a86dc24] FiniteDiff v2.20.0
  [53c48c17] FixedPointNumbers v0.8.4
  [59287772] Formatting v0.4.2
  [f6369f11] ForwardDiff v0.10.35
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.4.4
  [46192b85] GPUArraysCore v0.1.4
  [28b8d3ca] GR v0.72.4
  [c145ed77] GenericSchur v0.5.3
  [c27321d9] Glob v1.3.1
  [86223c79] Graphs v1.8.0
  [42e2da0e] Grisu v1.0.2
  [0b43b601] Groebner v0.3.4
  [d5909c97] GroupsCore v0.4.0
  [cd3eb016] HTTP v1.9.1
  [3e5b6fbb] HostCPUFeatures v0.1.14
  [e91730f6] Hungarian v0.7.0
  [34004b35] HypergeometricFunctions v0.3.16
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.3
  [18e54dd8] IntegerMathUtils v0.1.0
  [8197267c] IntervalSets v0.7.4
  [92d709cd] IrrationalConstants v0.2.2
  [c8e1da08] IterTools v1.4.0
  [42fd0dbc] IterativeSolvers v0.9.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [1019f520] JLFzf v0.1.5
  [692b3bcd] JLLWrappers v1.4.1
  [682c06a0] JSON v0.21.4
  [98e50ef6] JuliaFormatter v1.0.29
  [ccbc3e58] JumpProcesses v9.6.3
  [ef3ab10e] KLU v0.4.0
  [ba0b0d4f] Krylov v0.9.0
  [0b1a1467] KrylovKit v0.6.0
  [b964fa9f] LaTeXStrings v1.3.0
  [2ee39098] LabelledArrays v1.14.0
  [984bce1d] LambertW v0.4.6
  [23fbe1c1] Latexify v0.16.0
  [10f19ff3] LayoutPointers v0.1.14
  [50d2b5c4] Lazy v0.15.1
  [2d8b4e74] LevyArea v1.0.0
  [d3d80556] LineSearches v7.2.0
  [7a12625a] LinearMaps v3.10.0
  [7ed4a6bd] LinearSolve v1.42.0
  [2ab3a3ac] LogExpFunctions v0.3.23
  [e6f89c97] LoggingExtras v1.0.0
  [bdcacae8] LoopVectorization v0.12.159
  [1914dd2f] MacroTools v0.5.10
  [d125e4d3] ManualMemory v0.1.8
  [99c1a7ee] MatrixEquations v2.2.9
  [48965c70] MatrixPencils v1.7.6
  [739be429] MbedTLS v1.1.7
  [442fdcdd] Measures v0.3.2
  [e1d29d7a] Missings v1.1.0
  [961ee093] ModelingToolkit v8.55.1
  [16a59e39] ModelingToolkitStandardLibrary v1.16.0
  [0987c9cc] MonteCarloMeasurements v1.1.4
  [46d2c3a1] MuladdMacro v0.2.4
  [102ac46a] MultivariatePolynomials v0.4.7
  [d8a4904e] MutableArithmetics v1.3.0
  [d41bc354] NLSolversBase v7.8.3
  [2774e3e8] NLsolve v4.5.1
  [77ba4419] NaNMath v1.0.2
  [8913a72c] NonlinearSolve v1.6.0
  [6fe1bfb0] OffsetArrays v1.12.9
  [4d8831e6] OpenSSL v1.4.1
  [429524aa] Optim v1.7.5
  [bac558e1] OrderedCollections v1.6.0
  [1dea7af3] OrdinaryDiffEq v6.51.1
  [90014a1f] PDMats v0.11.17
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.5.8
  [b98c9c47] Pipe v1.3.0
  [ccf2f8ad] PlotThemes v3.1.0
  [995b91a9] PlotUtils v1.3.5
  [91a5bcdd] Plots v1.38.11
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.3
  [1d0040c9] PolyesterWeave v0.2.1
  [f27b6e38] Polynomials v3.2.11
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.12
  [aea7be01] PrecompileTools v1.1.1
  [21216c6a] Preferences v1.4.0
  [27ebfcd6] Primes v0.5.3
  [1fd47b50] QuadGK v2.8.2
  [74087812] Random123 v1.6.1
  [fb686558] RandomExtensions v0.4.3
  [e6cf234a] RandomNumbers v1.5.3
  [3cdcf5f2] RecipesBase v1.3.4
  [01d81517] RecipesPipeline v0.6.12
  [731186ca] RecursiveArrayTools v2.38.4
  [f2c3362d] RecursiveFactorization v0.2.18
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v1.0.0
  [ae029012] Requires v1.3.0
  [ae5879a3] ResettableStacks v1.1.1
  [79098fc4] Rmath v0.7.1
  [21fd56a4] RobustAndOptimalControl v0.4.24
  [7e49a35a] RuntimeGeneratedFunctions v0.5.7
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.38
  [0bca4576] SciMLBase v1.91.7
  [e9a6253c] SciMLNLSolve v0.1.6
  [c0aeaf25] SciMLOperators v0.2.4
  [6c6a2e73] Scratch v1.2.0
  [efcf1570] Setfield v1.1.1
  [992d4aef] Showoff v1.0.3
  [777ac1f9] SimpleBufferStream v1.1.0
  [727e6d20] SimpleNonlinearSolve v0.1.14
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [66db9d55] SnoopPrecompile v1.0.3
  [a2af1166] SortingAlgorithms v1.1.0
⌅ [47a9eef4] SparseDiffTools v1.31.0
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.2.0
  [aedffcd0] Static v0.8.7
  [0d7ed370] StaticArrayInterface v1.4.0
  [90137ffa] StaticArrays v1.5.24
  [1e83bf80] StaticArraysCore v1.4.0
  [82ae8749] StatsAPI v1.6.0
⌅ [2913bbd2] StatsBase v0.33.21
  [4c63d2b9] StatsFuns v1.3.0
  [9672c7b4] SteadyStateDiffEq v1.15.0
  [789caeaf] StochasticDiffEq v6.60.0
  [7792a7ef] StrideArraysCore v0.4.14
  [c3572dad] Sundials v4.17.0
  [2efcf032] SymbolicIndexingInterface v0.2.2
  [d1185830] SymbolicUtils v1.0.5
  [0c5d862f] Symbolics v5.3.1
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.10.1
  [62fd8b95] TensorCore v0.1.1
  [8290d209] ThreadingUtilities v0.5.1
  [a759f4b9] TimerOutputs v0.5.23
  [0796e94c] Tokenize v0.5.25
  [3bb67fe8] TranscodingStreams v0.9.13
  [a2a6695c] TreeViews v0.3.0
  [d5829a12] TriangularSolve v0.1.19
  [410a4b4d] Tricks v0.1.7
  [781d530d] TruncatedStacktraces v1.3.0
  [5c2747f8] URIs v1.4.2
  [3a884ed6] UnPack v1.0.2
  [1cfade01] UnicodeFun v0.4.1
  [1986cc42] Unitful v1.13.1
  [a7c27f48] Unityper v0.1.2
  [41fe7b60] Unzip v0.2.0
  [3d5dd08c] VectorizationBase v0.21.64
  [19fa3120] VertexSafeGraphs v0.2.0
  [700de1a5] ZygoteRules v0.2.3
  [6e34b625] Bzip2_jll v1.0.8+0
  [83423d85] Cairo_jll v1.16.1+1
  [2e619515] Expat_jll v2.4.8+0
  [b22a6f82] FFMPEG_jll v4.4.2+2
  [f5851436] FFTW_jll v3.3.10+0
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.10.4+0
  [559328eb] FriBidi_jll v1.0.10+0
  [0656b61e] GLFW_jll v3.3.8+0
  [d2c73de3] GR_jll v0.72.4+0
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.74.0+2
  [3b182d85] Graphite2_jll v1.3.14+0
  [2e76f6c2] HarfBuzz_jll v2.8.1+1
  [1d5cc7b8] IntelOpenMP_jll v2023.1.0+0
  [aacddb02] JpegTurbo_jll v2.1.91+0
  [c1c5ebd0] LAME_jll v3.100.1+0
  [88015f11] LERC_jll v3.0.0+1
  [dd4b983a] LZO_jll v2.10.1+0
⌅ [e9f186c6] Libffi_jll v3.2.2+1
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7e76a0d4] Libglvnd_jll v1.6.0+0
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.16.1+2
  [4b2f31a3] Libmount_jll v2.35.0+0
  [89763e89] Libtiff_jll v4.4.0+0
  [38a345b3] Libuuid_jll v2.36.0+0
⌅ [856f044c] MKL_jll v2022.2.0+0
  [e7412a2a] Ogg_jll v1.3.5+1
⌅ [458c3c95] OpenSSL_jll v1.1.20+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [30392449] Pixman_jll v0.40.1+0
  [ea2cea3b] Qt5Base_jll v5.15.3+2
  [f50d1b31] Rmath_jll v0.4.0+0
  [fb77eaff] Sundials_jll v5.2.1+0
  [a2964d1f] Wayland_jll v1.21.0+0
  [2381bf8a] Wayland_protocols_jll v1.25.0+0
  [02c8fc9c] XML2_jll v2.10.3+0
  [aed1982a] XSLT_jll v1.1.34+0
  [4f6342f7] Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] Xorg_libXau_jll v1.0.9+4
  [935fb764] Xorg_libXcursor_jll v1.2.0+4
  [a3789734] Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [d091e8ba] Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] Xorg_libXi_jll v1.7.10+4
  [d1454406] Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] Xorg_libxcb_jll v1.13.0+3
  [cc61e674] Xorg_libxkbfile_jll v1.1.0+4
  [12413925] Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] Xorg_xcb_util_jll v0.4.0+1
  [975044d2] Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] Xorg_xkbcomp_jll v1.4.2+4
  [33bec58e] Xorg_xkeyboard_config_jll v2.27.0+4
  [c5fb5394] Xorg_xtrans_jll v1.4.0+3
  [3161d3a3] Zstd_jll v1.5.5+0
⌅ [214eeab7] fzf_jll v0.29.0+0
  [a4ae2306] libaom_jll v3.4.0+0
  [0ac62f75] libass_jll v0.15.1+0
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [b53b4c65] libpng_jll v1.6.38+0
  [f27f6e37] libvorbis_jll v1.3.7+1
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [d8fb68d0] xkbcommon_jll v1.4.1+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.3
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.9.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics v1.9.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.0.2+0
  [deac9b47] LibCURL_jll v7.84.0+0
  [29816b5a] LibSSH2_jll v1.10.2+0
  [c8ffd9c3] MbedTLS_jll v2.28.2+0
  [14a3606d] MozillaCACerts_jll v2022.10.11
  [4536629a] OpenBLAS_jll v0.3.21+4
  [05823500] OpenLibm_jll v0.8.1+0
  [efcefdf7] PCRE2_jll v10.42.0+0
  [bea87d4a] SuiteSparse_jll v5.10.1+6
  [83775a58] Zlib_jll v1.2.13+0
  [8e850b90] libblastrampoline_jll v5.7.0+0
  [8e850ede] nghttp2_jll v1.48.0+0
  [3f19e933] p7zip_jll v17.4.0+0
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
```

**Closed by baggepinnen** 2023-05-11 09:26 UTC

**Comment by baggepinnen** [comment] 2023-05-11 18:05
The issue has been fixed in MatrixPencils and a new release of that package is pending, once merged, you should be able to update to the newly made release and hopefully enjoy a working `minreal` :)
